# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(default='uploads/default_img.png', upload_to='media/uploads')),
                ('slug', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerReviewdropdownvalues', to='Helpers.FAQdropdownMaster')),
            ],
        ),
    ]
