# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0002_customerreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreview',
            old_name='name',
            new_name='dropdownmaster',
        ),
        migrations.AddField(
            model_name='customerreview',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
