# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0004_customerreview_profile_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('front_image', models.ImageField(default='uploads/default_img.png', upload_to='media/uploads')),
                ('back_image', models.ImageField(default='uploads/default_img.png', upload_to='media/uploads')),
                ('slug', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dropdownmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreditCard', to='Helpers.FAQdropdownMaster')),
            ],
        ),
    ]
