# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-21 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0005_cardview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorydropdownValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dropdownmaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Helpers.FAQdropdownMaster')),
            ],
        ),
        migrations.RemoveField(
            model_name='cardview',
            name='dropdownmaster',
        ),
        migrations.DeleteModel(
            name='CardView',
        ),
    ]
