# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Helpers', '0006_auto_20180921_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlynews', models.BooleanField(default=False)),
                ('product_allyHealth_updates', models.BooleanField(default=False)),
                ('alerts_reminders', models.BooleanField(default=False)),
                ('appointment_reminders_updates', models.BooleanField(default=False)),
                ('message_alerts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailSettings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
