# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-17 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0008_pushnotification_smssetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, default='uploads/default_img.png', null=True, upload_to='media/uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='emailsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
