"""
Django settings for AllyHealth project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*wkf%x(-s2slw!z#+=zdd56&l0ot--m93m7(9yq6vif3vw5*mv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_swagger',
    # apps
    'AllyUsers',
    'Helpers',
    'ActivityLogs',
    'Mdlive',
    'SalesForce',

    # third party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'djcelery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AllyHealth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AllyHealth.wsgi.application'


EMAIL_CONFIG_ENCRYPTED_KEY = 'allyhealthEmailEncriptionKey'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

try:
  from settings_local import *
except Exception as e:
  pass



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'AllyUsers.CustomUser'

# media settings

MEDIA_URL = '/'
STATIC_URL = '/static/'





# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/



CORS_ALLOW_HEADERS = (
        'x-requested-with',
        'content-type',
        'accept',
        'accept-encoding',
        'dnt',
        'user-agent',
        'origin',
        'authorization',
        'x-csrftoken'
    )


CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True



SALESFORCE_CREDENTIALS = {
    'client_id' : '3MVG9CVKiXR7Ri5oMo1LC4IOnZMTwSzcszn73YfQAMMCDZdMVj_xNj6AGMdqy7PGHLUaiHveJwXXaVcGoc0HI',
    'client_secret' : '8627609994903466851',
    'username': '',
    # 'password' : 'ally@4321',
    'security_token': '',
    # 'redirect_uri':'https://allyhealth.theclientdemos.com/salesforce/redirecturl/',

    'access_token': ''
}

SALESFORCE_BASE_URL = "https://na29.salesforce.com/services/data/v43.0/"



# MDLIVE CREDENTIALS
MDLIVE_CREDENTIALS = {
#     'client_id' : '',
#     'client_secret' : '',
    'api_key': '014a3e906ebf0c43635c',
    'api_password': 'b22b7e2429d209a6600',
    
}

MDLIVE_BASE_URL = "https://stage-rest-api.mdlive.com/"


PAGESIZE = 10
REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        
    ),
    'DEFAULT_PERMISSION_CLASSES': (
 'rest_framework.permissions.IsAuthenticated',
 ),


}



# Celery settings
#celery confgiuration
BROKER_URL = "amqp://guest:guest@localhost:5672//"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'