# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0002_auto_20180911_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='AccountId',
            new_name='accountId',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Birthdate',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Contact_Id',
            new_name='contact_Id',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='mobilePhone',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Health_Insurance_Company',
            new_name='health_Insurance_Company',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Health_Insurance_Member_ID',
            new_name='health_Insurance_Member_ID',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='MailingPostalCode',
            new_name='subscriber_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_CreatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
