# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-13 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0003_auto_20180911_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Name',
            new_name='name',
        ),
    ]
