# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0004_auto_20180913_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_CreatedDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
