# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-15 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0005_auto_20180915_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
