# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-19 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0008_auto_20180919_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Feamle')], default=1, null=True),
        ),
    ]
