# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0010_auto_20180919_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=b'uploads/images.jpeg', upload_to=b'media/uploads'),
        ),
    ]
