# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0011_auto_20180919_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=b'images.jpeg', upload_to=b'media/uploads'),
        ),
    ]
