# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0012_auto_20180920_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=b'uploads/default_img.png', upload_to=b'media/uploads'),
        ),
    ]
