# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-21 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0006_auto_20180921_0620'),
        ('AllyUsers', '0013_auto_20180920_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(default=b'uploads/default_img.png', upload_to=b'media/uploads')),
                ('back_image', models.ImageField(default=b'uploads/default_img.png', upload_to=b'media/uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_currently_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_type', to='Helpers.CategorydropdownValues')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
