# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-05 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0014_usersavedcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
