# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0015_customuser_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='crypt_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'M', b'male'), (b'F', b'female')], max_length=2, null=True),
        ),
    ]
