# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0016_auto_20181011_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'male', b'male'), (b'female', b'female')], max_length=2, null=True),
        ),
    ]
