# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-17 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0009_auto_20181017_1035'),
        ('AllyUsers', '0018_auto_20181016_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_currently_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_image', to='Helpers.FileUpload')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_type', to='Helpers.CategorydropdownValues')),
                ('front', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_image', to='Helpers.FileUpload')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersavedcards',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usersavedcards',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSavedCards',
        ),
    ]
