# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0019_auto_20181017_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'M', b'male'), (b'F', b'female')], max_length=10, null=True),
        ),
    ]
