# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-12 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0020_auto_20181023_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdliveServiceApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_health', models.BooleanField(default=False)),
                ('health_wellness_coaching', models.BooleanField(default=False)),
                ('consult_a_specialist', models.BooleanField(default=False)),
                ('talk_to_a_counselor', models.BooleanField(default=False)),
                ('talk_to_a_doctor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mdliveserviceapi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mdlive_service_api', to=settings.AUTH_USER_MODEL),
        ),
    ]
