# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllyUsers', '0021_auto_20181112_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mdlive_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
