# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-06 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mdlive', '0004_auto_20181001_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdliveUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(blank=True, max_length=255, null=True)),
                ('user_time_to_live_minutes', models.TimeField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
