# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-06 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mdlive', '0005_mdliveusertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdliveusertoken',
            name='user_time_to_live_minutes',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
