# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-08 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mdlive', '0007_auto_20181006_1110'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='mdliveusertoken',
        #     name='user_id',
        # ),
        # migrations.AddField(
        #     model_name='mdliveregistration',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        # ),
    ]
