# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-08 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mdlive', '0008_auto_20181008_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdliveusertoken',
            old_name='user_id',
            new_name='sso_user_id',
        ),
        migrations.AddField(
            model_name='mdliveregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mdliveusertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mdliveusertoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mdliveusertoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sso_user_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
