# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mdlive', '0009_auto_20181008_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdliveregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mdlive_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
