# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-05 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mdlive', '0011_mdliveauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdliveauth',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mdlive_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
