# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mdlive', '0012_mdliveauth_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdliveAppAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_auth', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mdliveauth',
            name='user',
        ),
        migrations.DeleteModel(
            name='MdliveAuth',
        ),
    ]
