# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-13 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mdlive', '0013_auto_20181105_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdliveusertoken',
            old_name='jwt',
            new_name='m_jwt_token',
        ),
        migrations.RenameField(
            model_name='mdliveusertoken',
            old_name='sso_user_id',
            new_name='m_patient_id',
        ),
    ]
