# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-04 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesForce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForceTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('id_token', models.TextField(blank=True, null=True)),
                ('instance_url', models.URLField(blank=True, null=True)),
                ('issued_at', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('of_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_sales', to='SalesForce.SalesForceCode')),
            ],
        ),
    ]
