# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-05 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesForce', '0002_salesforcetokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResuableAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuable_access_token', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='salesforcetokens',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
