# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-13 11:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesForce', '0003_auto_20180905_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingSalesforceContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_r', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='user_email')),
                ('contact_number_r', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^-?[0-9]+$')])),
                ('zipcode_r', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName_r', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate_r', models.DateTimeField(blank=True, null=True)),
                ('health_Insurance_Company_r', models.CharField(blank=True, max_length=255, null=True)),
                ('health_Insurance_Member_ID_r', models.CharField(blank=True, max_length=255, null=True)),
                ('name_r', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_Id_r', models.CharField(blank=True, max_length=255, null=True)),
                ('accountId_r', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_CreatedDate_r', models.DateTimeField(blank=True, null=True)),
                ('subscriber_id_r', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
