# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesForce', '0005_auto_20180914_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingsalesforcecontact',
            name='birthdate_r',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkingsalesforcecontact',
            name='contact_CreatedDate_r',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
