# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-17 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesForce', '0006_auto_20180915_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingsalesforcecontact',
            name='contact_number_r',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
